name: Destroy Lambda Infra

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      #AWS CREDENTIALS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION}}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: myGitHubActions
      #Terraform execution
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Destroy
        run:  |
          cd terraform
          terraform apply -auto-approve
        env:
          TF_VAR_lambda_execution_role: ${{ secrets.LAMBDA_EXECUTION_ROLE }}
          TF_VAR_rds_endpoint: ${{ secrets.RDS_ENDPOINT }}
          TF_VAR_rds_db_name: ${{ vars.DB_NAME }}
          TF_VAR_subnet_a: ${{ vars.SUBNET_A }}
          TF_VAR_subnet_b: ${{ vars.SUBNET_B }}
          TF_VAR_security_group_lambda: ${{ vars.SG_CLUSTER_ECS }}